=== CMingTseng/mobicents/mobicents-examples/xmpp-test/dtd/slee-resource-adaptor-type-jar_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--

This is the provisional XML DTD for the JAIN SLEE 1.0 Resource Adaptor Type
jar file deployment desriptor. 

  <!DOCTYPE resource-adaptor-type-jar PUBLIC
        "-//Sun Microsystems, Inc.//DTD JAIN SLEE Resource Adaptor Type 1.0//EN"
        "http://java.sun.com/dtd/slee-resource-adaptor-type-jar_1_0.dtd">

-->

<!ELEMENT resource-adaptor-type-jar (description?, resource-adaptor-type+)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT resource-adaptor-type (description?, resource-adaptor-type-name,
          resource-adaptor-type-vendor, resource-adaptor-type-version,
          resource-adaptor-type-classes?, event-type-ref*)>

<!ELEMENT resource-adaptor-type-name (#PCDATA)>
<!ELEMENT resource-adaptor-type-vendor (#PCDATA)>
<!ELEMENT resource-adaptor-type-version (#PCDATA)>

<!ELEMENT resource-adaptor-type-classes (description?, activity-type*, 
          activity-context-interface-factory-interface?, 
          resource-adaptor-interface?)>

<!ELEMENT activity-type (description?, activity-type-name)>
<!ELEMENT activity-type-name (#PCDATA)>

<!ELEMENT activity-context-interface-factory-interface (description?,
          activity-context-interface-factory-interface-name)>
<!ELEMENT activity-context-interface-factory-interface-name (#PCDATA)>

<!ELEMENT resource-adaptor-interface (description?, 
          resource-adaptor-interface-name)>
<!ELEMENT resource-adaptor-interface-name (#PCDATA)>

<!ELEMENT event-type-ref (event-type-name, event-type-vendor, event-type-version)>
<!ELEMENT event-type-name (#PCDATA)>
<!ELEMENT event-type-vendor (#PCDATA)>
<!ELEMENT event-type-version (#PCDATA)>

<!ATTLIST resource-adaptor-type-jar id ID #IMPLIED>
<!ATTLIST description id ID #IMPLIED>
<!ATTLIST resource-adaptor-type id ID #IMPLIED>
<!ATTLIST resource-adaptor-type-name id ID #IMPLIED>
<!ATTLIST resource-adaptor-type-vendor id ID #IMPLIED>
<!ATTLIST resource-adaptor-type-version id ID #IMPLIED>
<!ATTLIST resource-adaptor-type-classes id ID #IMPLIED>
<!ATTLIST activity-type id ID #IMPLIED>
<!ATTLIST activity-type-name id ID #IMPLIED>
<!ATTLIST activity-context-interface-factory-interface id ID #IMPLIED>
<!ATTLIST activity-context-interface-factory-interface-name id ID #IMPLIED>
<!ATTLIST resource-adaptor-interface id ID #IMPLIED>
<!ATTLIST resource-adaptor-interface-name id ID #IMPLIED>
<!ATTLIST event-type-ref id ID #IMPLIED>
<!ATTLIST event-type-name id ID #IMPLIED>
<!ATTLIST event-type-vendor id ID #IMPLIED>
<!ATTLIST event-type-version id ID #IMPLIED>

=== CMingTseng/mobicents/servers/jain-slee/resources/diameter/cca/ratype/src/main/resources/META-INF/resource-adaptor-type-jar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE resource-adaptor-type-jar PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Resource Adaptor Type 1.0//EN" "http://java.sun.com/dtd/slee-resource-adaptor-type-jar_1_0.dtd">

<resource-adaptor-type-jar>
	<description />

	<resource-adaptor-type>
		<description>Diameter CCA RA Type</description>
		<resource-adaptor-type-name>Diameter CCA</resource-adaptor-type-name>
		<resource-adaptor-type-vendor>java.net</resource-adaptor-type-vendor>
		<resource-adaptor-type-version>0.8.1</resource-adaptor-type-version>

		<resource-adaptor-type-classes>
			<activity-type>
				<activity-type-name>
				  net.java.slee.resource.diameter.cca.CreditControlClientSession
				</activity-type-name>
			</activity-type>

      <activity-type>
        <activity-type-name>
          net.java.slee.resource.diameter.cca.CreditControlServerSession
        </activity-type-name>
      </activity-type>

      <activity-type>
        <activity-type-name>
          net.java.slee.resource.diameter.base.DiameterActivity
        </activity-type-name>
      </activity-type>

			<activity-context-interface-factory-interface>
			  <activity-context-interface-factory-interface-name>
			    net.java.slee.resource.diameter.cca.CreditControlActivityContextInterfaceFactory
			  </activity-context-interface-factory-interface-name>
			</activity-context-interface-factory-interface>
			
			<resource-adaptor-interface>
			  <resource-adaptor-interface-name>
			    net.java.slee.resource.diameter.cca.CreditControlProvider
			  </resource-adaptor-interface-name>
			</resource-adaptor-interface>
		</resource-adaptor-type-classes>

    <event-type-ref>
        <event-type-name>net.java.slee.resource.diameter.cca.events.CreditControlRequestEvent</event-type-name>
        <event-type-vendor>java.net</event-type-vendor>
        <event-type-version>0.8</event-type-version>
    </event-type-ref>

    <event-type-ref>
        <event-type-name>net.java.slee.resource.diameter.cca.events.CreditControlRequestInitial</event-type-name>
        <event-type-vendor>java.net</event-type-vendor>
        <event-type-version>0.8</event-type-version>
    </event-type-ref>

    <event-type-ref>
        <event-type-name>net.java.slee.resource.diameter.cca.events.CreditControlRequestUpdate</event-type-name>
        <event-type-vendor>java.net</event-type-vendor>
        <event-type-version>0.8</event-type-version>
    </event-type-ref>

    <event-type-ref>
        <event-type-name>net.java.slee.resource.diameter.cca.events.CreditControlRequestTermination</event-type-name>
        <event-type-vendor>java.net</event-type-vendor>
        <event-type-version>0.8</event-type-version>
    </event-type-ref>

    <event-type-ref>
        <event-type-name>net.java.slee.resource.diameter.cca.events.CreditControlAnswer</event-type-name>
        <event-type-vendor>java.net</event-type-vendor>
        <event-type-version>0.8</event-type-version>
    </event-type-ref>
	</resource-adaptor-type>
	
</resource-adaptor-type-jar>

=== CMingTseng/mobicents/servers/jain-slee/resources/rules/ratype/src/main/resources/META-INF/resource-adaptor-type-jar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE resource-adaptor-type-jar PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Resource Adaptor Type 1.0//EN" "http://java.sun.com/dtd/slee-resource-adaptor-type-jar_1_0.dtd">

<resource-adaptor-type-jar>
    <description />
    <resource-adaptor-type>
        <description>Rules resource adaptor type</description>
        <resource-adaptor-type-name>
            RulesResourceAdaptorType
        </resource-adaptor-type-name>
        <resource-adaptor-type-vendor>
            org.mobicents
        </resource-adaptor-type-vendor>
        <resource-adaptor-type-version>
            1.0
        </resource-adaptor-type-version>
        <resource-adaptor-type-classes>
            <activity-type>
                <activity-type-name>
                    org.mobicents.slee.resource.rules.ratype.RulesSession
                </activity-type-name>
            </activity-type>
            
            <activity-context-interface-factory-interface>
                <activity-context-interface-factory-interface-name>
                    org.mobicents.slee.resource.rules.ratype.RulesActivityContextInterfaceFactory
                </activity-context-interface-factory-interface-name>
            </activity-context-interface-factory-interface>
            
            <resource-adaptor-interface>
                <resource-adaptor-interface-name>
                    org.mobicents.slee.resource.rules.ratype.RulesProvider
                </resource-adaptor-interface-name>
            </resource-adaptor-interface>
        </resource-adaptor-type-classes>        
        
        <event-type-ref>
            <event-type-name>
                org.mobicents.slee.rules.FactAsserted
            </event-type-name>
            <event-type-vendor>org.mobicents</event-type-vendor>
            <event-type-version>1.0</event-type-version>
        </event-type-ref>
    </resource-adaptor-type>
</resource-adaptor-type-jar>

=== CMingTseng/mobicents/core/legacy/tests/ra/dummyra/descriptors/ratype/resource-adaptor-type-jar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE resource-adaptor-type-jar PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Resource Adaptor Type 1.0//EN" "http://java.sun.com/dtd/slee-resource-adaptor-type-jar_1_0.dtd">

<resource-adaptor-type-jar>
	<description />
	<resource-adaptor-type>
		<description>Dummy resource adaptor type</description>
		<resource-adaptor-type-name>
			DummyResourceAdaptorType
		</resource-adaptor-type-name>
		<resource-adaptor-type-vendor>
			org.mobicents
		</resource-adaptor-type-vendor>
		<resource-adaptor-type-version>
			1.0
		</resource-adaptor-type-version>
		<resource-adaptor-type-classes>
			<activity-type>
				<activity-type-name>
					org.mobicents.slee.resource.dummy.ratype.DummyActivity
				</activity-type-name>
			</activity-type>

			<activity-context-interface-factory-interface>
				<activity-context-interface-factory-interface-name>
					org.mobicents.slee.resource.dummy.ra.DummyActivityContextInterfaceFactoryImpl
				</activity-context-interface-factory-interface-name>
			</activity-context-interface-factory-interface>

			<resource-adaptor-interface>
				<resource-adaptor-interface-name>
					org.mobicents.slee.resource.dummy.ra.DummyResourceAdaptor
				</resource-adaptor-interface-name>
			</resource-adaptor-interface>
		</resource-adaptor-type-classes>


		<event-definition>
			<event-type-name>
				org.mobicents.slee.resource.dummy.Event
			</event-type-name>
			<event-type-vendor>net.java</event-type-vendor>
			<event-type-version>1.0</event-type-version>
		</event-definition>
	</resource-adaptor-type>
	<event-definition>
		<event-type-name>
			org.mobicents.slee.resource.dummy.Event_2
		</event-type-name>
		<event-type-vendor>net.java</event-type-vendor>
		<event-type-version>1.0</event-type-version>
	</event-definition>
	<event-definition>
		<event-type-name>
			org.mobicents.slee.resource.dummy.Event_3
		</event-type-name>
		<event-type-vendor>net.java</event-type-vendor>
		<event-type-version>1.0</event-type-version>
	</event-definition>
	<event-definition>
		<event-type-name>
			org.mobicents.slee.resource.dummy.Event_4
		</event-type-name>
		<event-type-vendor>net.java</event-type-vendor>
		<event-type-version>1.0</event-type-version>
	</event-definition>
	<event-definition>
		<event-type-name>
			org.mobicents.slee.resource.dummy.Event_5
		</event-type-name>
		<event-type-vendor>net.java</event-type-vendor>
		<event-type-version>1.0</event-type-version>
	</event-definition>
</resource-adaptor-type-jar>

=== CMingTseng/mobicents/servers/jain-slee/tools/maven-archetypes/jain-slee-basic-ra/src/main/resources/archetype-resources/ratype/src/main/resources/META-INF/resource-adaptor-type-jar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE resource-adaptor-type-jar PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Resource Adaptor Type 1.0//EN" "http://java.sun.com/dtd/slee-resource-adaptor-type-jar_1_0.dtd">

<resource-adaptor-type-jar>
	<description />
	<resource-adaptor-type>
		<description>Dummy resource adaptor type</description>
		<resource-adaptor-type-name>DummyResourceAdaptorType</resource-adaptor-type-name>
		<resource-adaptor-type-vendor>${groupId}</resource-adaptor-type-vendor>
		<resource-adaptor-type-version>${version}</resource-adaptor-type-version>
		<resource-adaptor-type-classes>
			<activity-type>
				<activity-type-name>${package}.DummyActivity</activity-type-name>
			</activity-type>
			<activity-context-interface-factory-interface>
				<activity-context-interface-factory-interface-name>${package}.DummyActivityContextInterfaceFactory</activity-context-interface-factory-interface-name>
			</activity-context-interface-factory-interface>
		</resource-adaptor-type-classes>

		<event-type-ref>
			<event-type-name>${package}.Event</event-type-name>
			<event-type-vendor>${groupId}</event-type-vendor>
			<event-type-version>${version}</event-type-version>
		</event-type-ref>
		<event-type-ref>
			<event-type-name>${package}.Event_2</event-type-name>
			<event-type-vendor>${groupId}</event-type-vendor>
			<event-type-version>${version}</event-type-version>
		</event-type-ref>
		<event-type-ref>
			<event-type-name>${package}.Event_3</event-type-name>
			<event-type-vendor>${groupId}</event-type-vendor>
			<event-type-version>${version}</event-type-version>
		</event-type-ref>
		<event-type-ref>
			<event-type-name>${package}.Event_4</event-type-name>
			<event-type-vendor>${groupId}</event-type-vendor>
			<event-type-version>${version}</event-type-version>
		</event-type-ref>
		<event-type-ref>
			<event-type-name>${package}.Event_5</event-type-name>
			<event-type-vendor>${groupId}</event-type-vendor>
			<event-type-version>${version}</event-type-version>
		</event-type-ref>
	</resource-adaptor-type>
</resource-adaptor-type-jar>
