=== CMingTseng/mobicents/branches/mgcpcontrol/slee-service_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?><!--This is the XML DTD for the JAIN SLEE 1.0 service component deploymentdesriptor.  All JAIN SLEE 1.0 service component deployment descriptors mustinclude a DOCTYPE of the following form:  <!DOCTYPE service-xml PUBLIC        "-//Sun Microsystems, Inc.//DTD JAIN SLEE Service 1.0//EN"        "http://java.sun.com/dtd/slee-service_1_0.dtd">--><!--The service-xml element is the root element of the service componentdeployment descriptor.  It contains an optional description about the profilespecification jar file and one or more service definitions.--><!ELEMENT service-xml (description?, service+)><!--The service element defines a service component.  It contains an optionaldescription about the service being defined, the name, vendor, and version ofthe service, a reference to the root sbb type, a default priority for the rootsbb, and optional names of an address profile table and resource info profiletable used by the service.Used in: service-xml--><!ELEMENT service (description?, service-name, service-vendor,           service-version, root-sbb, default-priority, address-profile-table?,          resource-info-profile-table?)><!--The description element may contain any descriptive text about the parentelement.Used in: service-xml, service, root-sbb--><!ELEMENT description (#PCDATA)><!--The service-name element contains the name of the service component.Used in: serviceExample:    <service-name>MyService</service-name>--><!ELEMENT service-name (#PCDATA)><!--The service-vendor element contains the vendor of the service component.Used in: serviceExample:    <service-vendor>My Company, Inc.</service-vendor>--><!ELEMENT service-vendor (#PCDATA)><!--The service-version element contains the version of the service component.The version number typically should have the general form"major-version.minor-version".Used in: serviceExample:    <service-version>1.0</service-version>--><!ELEMENT service-version (#PCDATA)><!--The root-sbb element defines the sbb component type of the service's root sbb.It contains an optional description about the root sbb, and the name, vendor,and version of the root sbb.Used in: service--><!ELEMENT root-sbb (description?, sbb-name, sbb-vendor, sbb-version)><!--The sbb-name element contains the name of an sbb component.Used in: root-sbbExample:    <sbb-name>MySbb</sbb-name>--><!ELEMENT sbb-name (#PCDATA)><!--The sbb-vendor element contains the vendor of an sbb component.Used in: root-sbbExample:    <sbb-name>My Company, Inc.</sbb-name>--><!ELEMENT sbb-vendor (#PCDATA)><!--The sbb-version element contains the version of an sbb component.Used in: root-sbbExample:    <sbb-name>1.0</sbb-name>--><!ELEMENT sbb-version (#PCDATA)><!-- The default-priority element contains the default priority of the root sbb.The default priority must lie in the range -128 thru 127.Used in: serviceExample:    <default-priority>0</default-priority>--><!ELEMENT default-priority (#PCDATA)><!--The address-profile-table element contains the name of the address profiletable used by the service.Used in: serviceExample:    <address-profile-table>MyAddresses</address-profile-table>--><!ELEMENT address-profile-table (#PCDATA)><!--The resource-info-profile-table element contains the name of the resource infoprofile table used by the service.Used in: serviceExample:    <resource-info-profile-table>MyResourceInfo</resourc-info-profile-table>--><!ELEMENT resource-info-profile-table (#PCDATA)><!-- The ID mechanism is to allow tools that produce additional deploymentinformation (ie. information beyond that contained by the standard SLEEdeployment descriptors) to store the non-standard information in a separatefile, and easily refer from those tools-specific files to the information inthe standard deployment descriptor.  The SLEE architecture does not allow thetools to add the non-standard information into the SLEE-defined deploymentdescriptors. --><!ATTLIST service-xml id ID #IMPLIED><!ATTLIST service id ID #IMPLIED><!ATTLIST description id ID #IMPLIED><!ATTLIST service-name id ID #IMPLIED><!ATTLIST service-vendor id ID #IMPLIED><!ATTLIST service-version id ID #IMPLIED><!ATTLIST root-sbb id ID #IMPLIED><!ATTLIST sbb-name id ID #IMPLIED><!ATTLIST sbb-vendor id ID #IMPLIED><!ATTLIST sbb-version id ID #IMPLIED><!ATTLIST default-priority id ID #IMPLIED><!ATTLIST address-profile-table id ID #IMPLIED><!ATTLIST resource-info-profile-table id ID #IMPLIED>

=== CMingTseng/mobicents/servers/jain-slee/tck/jain-slee-1.0/testsuite/tests/src/org/mobicents/sleetests/runtime/ActivityContext/TestPTI01-META-INF/service-jar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
 
<!DOCTYPE service-xml PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Service 1.0//EN" "http://java.sun.com/dtd/slee-service_1_0.dtd">
 
<service-xml>
    <service>
        <service-name>TestPTI01Service</service-name>
        <service-vendor>ptinovacao.pt</service-vendor>
        <service-version>1.0</service-version>
        <root-sbb>
            <sbb-name>TestPTI01Sbb</sbb-name>
            <sbb-vendor>ptinovacao.pt</sbb-vendor>
            <sbb-version>1.0</sbb-version>
        </root-sbb>
        <default-priority>0</default-priority>
    </service>
</service-xml>

=== CMingTseng/mobicents/examples/call-controller/src/org/mobicents/slee/examples/controller/callcontroller-service.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE service-xml PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Service 1.0//EN"
                             "http://java.sun.com/dtd/slee-service_1_0.dtd">
<service-xml>
    <service>
        <description>Call Controller Service</description>
        <service-name>CallControllerService</service-name>
        <service-vendor>org.mobicents</service-vendor>
        <service-version>0.1</service-version>
        <root-sbb>
            <description>This SBB is going to control the CallBlocking,
                Forwarding and Voicemail service</description>
            <sbb-name>CallControllerSbb</sbb-name>
            <sbb-vendor>org.mobicents</sbb-vendor>
            <sbb-version>0.1</sbb-version>
        </root-sbb>
        <default-priority>0</default-priority>
    </service>
</service-xml>

=== CMingTseng/mobicents/servers/jain-slee/core/legacy/tests/tests/src/org/mobicents/sleetests/sbb/cmp/setSideEffects/META-INF/CMPTest-service-jar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE service-xml PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Service 1.0//EN" "slee-service_1_0.dtd">

<service-xml>
    <service>
        <service-name>CMPTest</service-name>
   	<service-vendor>na</service-vendor>
        <service-version>1.0</service-version>
        <root-sbb>
            <sbb-name>CMPTestRootSbb</sbb-name>
       	    <sbb-vendor>na</sbb-vendor>
            <sbb-version>1.0</sbb-version>
        </root-sbb>
        <default-priority>0</default-priority>
    </service>
</service-xml>

=== CMingTseng/mobicents/resources/sipra/tests/src/org/mobicents/sleetests/siptests/DialogTerminated_C3/META-INF/service-jar.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE service-xml PUBLIC "-//Sun Microsystems, Inc.//DTD JAIN SLEE Service 1.0//EN" "slee-service_1_0.dtd">

<service-xml>
    <service>
        <service-name>DialogTerminated_C3TestService</service-name>
   	<service-vendor>mobicents</service-vendor>
        <service-version>0.1</service-version>
        <root-sbb>
            <sbb-name>DialogTerminated_C3TestSbb</sbb-name>
       	    <sbb-vendor>mobicents</sbb-vendor>
            <sbb-version>0.1</sbb-version>
        </root-sbb>
        <default-priority>0</default-priority>
    </service>
</service-xml>
