=== CMingTseng/mobicents/servers/jain-slee/resources/sip/tests/src/slee-tck-test-description_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
This is the XML DTD for the JAIN SLEE TCK 1.0 test description files.

Each test description file must contain a DOCTYPE of the following form:
 <!DOCTYPE test-description SYSTEM "http://www.opencloud.com/dtd/slee-tck-test-description_1_0.dtd">
-->

<!--
The test-description element is the root element of the
JAIN SLEE TCK 1.0 test description file.
A test description file can only contain one test-description.
-->
<!ELEMENT test-description (title, description?, executeClass, executeArgs?, assertion+,
                            assume-assertion*, timeout-multiplier?, property*, keyword*)>

<!-- A human readable title for the test -->
<!ELEMENT title (#PCDATA)>

<!-- An optional description of the test -->
<!ELEMENT description (#PCDATA)>

<!-- The class name of the test class to run.
     The given class must implement the SleeTCKTest interface -->
<!ELEMENT executeClass (#PCDATA)>

<!-- The arguments to pass to the test class -->
<!ELEMENT executeArgs (#PCDATA)>

<!-- Each test description must reference at least one assertion which be tested.
     The "id" attribute must contain a valid assertion number -->
<!ELEMENT assertion EMPTY>

<!-- The test may assume that certain assertions have already tested, and
     can reference these using the assume-assertion element.
     The "id" attribute must contain a valid assertion number.
     This information allows the test suite to be automatically ordered
     and filtered at runtime -->
<!ELEMENT assume-assertion EMPTY>

<!-- If specified, the timeout for the test is the default timeout
     multiplied by the given value.
     If not specified, the timeout for the test is the same as the default timeout.
     The timeout-multiplier must be a positive real number.
     The default timeout is set via the JAIN SLEE TCK configuration interview.
     -->
<!ELEMENT timeout-multiplier (#PCDATA)>

<!-- Tests can define custom properties to parameterize the test class.
     The property name element takes two attributes: "name" and "value".
     The property name:
     (1) must not appear more than once within a single test description.
     (2) must not be a number
     (3) must not be one of the following:
	"title","description","executeClass","keywords","assertions","assume-assertions",
        "assertion","assume-assertion","timeout","id","classDir",
        "executeArgs","source","sources","keyword","property","name","value"
      -->
<!ELEMENT property EMPTY>

<!-- Tests can reference keywords to control grouping and selection of tests
     (not currently used)-->
<!ELEMENT keyword (#PCDATA)>

<!ATTLIST assertion id ID #REQUIRED>
<!ATTLIST assume-assertion id ID #REQUIRED>
<!ATTLIST property name  ID #REQUIRED
		   value CDATA #REQUIRED>

=== CMingTseng/mobicents/core/jain-slee-1.0-tck/testsuite/tests/javax/slee/Address/Test3333Test.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
 
<!DOCTYPE test-description SYSTEM "http://www.opencloud.com/dtd/slee-tck-test-description_1_0.dtd">
 
<test-description>
 
 <title>Test3333Test</title>
 <executeClass>com.opencloud.sleetck.lib.testsuite.javax.slee.Address.Test3333Test</executeClass>
 <assertion id="3333"/>
 <assertion id="3336"/>
 <assertion id="3338"/>
 <assertion id="3340"/>
 <assertion id="3342"/>
 <assertion id="3344"/>
 <assertion id="3346"/>
 <assertion id="3348"/>
 <assertion id="3350"/>
 <assertion id="3352"/>
</test-description>

=== CMingTseng/mobicents/core/jain-slee-1.0-tck/testsuite/tests/profiles/profilerefs/ManyToManyProfilesTest.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE test-description SYSTEM "http://www.opencloud.com/dtd/slee-tck-test-description_1_0.dtd">

<test-description>

 <title>ManyToManyProfilesTest</title>
 <executeClass>com.opencloud.sleetck.lib.testsuite.profiles.profilerefs.ManyToManyProfilesTest</executeClass>
 <assertion id="914"/>
 <assertion id="988"/>
 <assertion id="1977"/>
 <assume-assertion id="913"/>
 <property name="profileSpecDUPath" value="profiles.ManyToManyProfileSpec-du.jar"/>

</test-description>
